[package]
name = "canvas_auto_grader_for_java"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canvasapi = "0.5.0"
config = "0.13.3"
tokio = "1.27.0"
